### ISSUE TITLE
For some reason, neko.py can't be found

### ISSUE THREAD

**Issue by danglingptr0x0** [RangerDigital/neko-box#2]
Hey,

I just tried using this workflow, but Python claims that it couldn't find `neko.py`.

What could have gone wrong?

`python: can't open file '/github/workspace/./neko/neko.py': [Errno 2] No such file or directory`

I used the exact same workflow as you in the `README.md` file. I have verified that all the details are correct (repo secrets).

**Comment by danglingptr0x0** [comment]
UPDATE: Different exception now:
```
Run rangerdigital/neko-box@master
/usr/bin/docker run --name a33c1db4e71bae65a4fb8bc8afa82def049e0_84c630 --label 8a33c1 --workdir /github/workspace --rm -e INPUT_GH_TOKEN -e INPUT_GIST_ID -e INPUT_ANILIST_USERNAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/simonSlamka/simonSlamka":"/github/workspace" 8a33c1:db4e71bae65a4fb8bc8afa82def049e0
Traceback (most recent call last):
  File "/github/workspace/./neko/neko.py", line 118, in <module>
    main()
  File "/github/workspace/./neko/neko.py", line 89, in main
    activity = run_query(query, variables)["Activity"]
  File "/github/workspace/./neko/neko.py", line 38, in run_query
    raise Exception("AniList query failed, check the provided username!")
Exception: AniList query failed, check the provided username!
```

**Comment by danglingptr0x0** [comment]
Fixed, the issue was missing activity. Thanks
